version: '3'

services:
  icecast:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./icecast.xml:/etc/icecast.xml
      - ./index.html:/usr/share/icecast/web/index.html

  nginx:
    image: nginx:latest
    ports:
      - "90:80"
    depends_on:
      - icecast
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
